image: gitlab-registry-dev.cern.ch/ctojeiro/mkdocs-to-gitlabpagessite-migration:latest
variables:
  GIT_SUBMODULE_STRATEGY: recursive
pages:
  script:
    - if [[ -f requirements.txt ]]; then pip install -r requirements.txt; fi;
    - mkdocs build -d public
  artifacts:
    paths:
    - public
    expire_in: 1 hour
  only:
  - master