site_name: Birmingham Instrumentation Laboratory for Particle physics and Applications
site_description: Documenting our tools
site_author: BILPA Group
site_url: https://bilpa.docs.cern.ch/

repo_name: GitLab
repo_url: https://gitlab.cern.ch/bilpa/wiki
edit_uri: 'blob/master/docs'

theme:
  name: material

markdown_extensions:
  - attr_list

plugins:
  - search
nav:
    - Welcome: index.md
    - 'Official Page': http://www.ep.ph.bham.ac.uk/general/SiliconLab/index.html
    - 'Starter Guides':
      - 'ATLAS' : guides/atlas.md
      - 'Computing' : guides/computing.md
      - 'Electronics' : guides/electronics.md
      - 'Particle Physics' : guides/pp.md
      - 'ROOT' : guides/root.md
      - 'Silicon Detectors' : guides/silicon.md
    - 'Procedures' :
      - 'Training' : procedures/training.md
      - 'Shutdown' : procedures/shutdown.md
    - 'Monitoring' :
      - 'InfluxDB + GrafAna' : monitoring/influx.md
    - 'MC40 Irradiation Facility':
      - 'Documentation' : mc40/docs.md
    - 'ITk Strips':
      - 'References': itkstrips/references.md
      - 'Cold Jig':
          - 'Local Instructions' : itkstrips/coldjig/local.md
          - 'Thermal Cycling' : itkstrips/coldjig/thermalcycling.md
          - 'Cold Noise Testing' : itkstrips/coldjig/cntesting.md
      - 'Local Guides':
          - 'Hybrid-Building Slides' : https://indico.cern.ch/event/1303151/contributions/5480159/attachments/2682043/4652810/BHM_Hybrid_Building_BILPA_2023_07_11.pdf
      - 'Hybrid and Module Assembly':
          - 'Simple Linux Commands': itkstrips/hybrid_and_module_building/linuxcommands.md
          - 'Magic Spreadsheets':
              - 'Introduction': itkstrips/hybrid_and_module_building/magicspreadsheets/magicspreadsheets_header.md
              - 'Hybrid Gluing': itkstrips/hybrid_and_module_building/magicspreadsheets/magicspreadsheets_hybridassembly.md
              - 'Module Gluing': itkstrips/hybrid_and_module_building/magicspreadsheets/magicspreadsheets_moduleassembly.md
              - 'Hybrid Wire Bonding': itkstrips/hybrid_and_module_building/magicspreadsheets/magicspreadsheets_hybridwirebonding.md
              - 'Module Wire Bonding': itkstrips/hybrid_and_module_building/magicspreadsheets/magicspreadsheets_modulewirebonding.md
          - 'Metrology':
              - 'Introduction': itkstrips/hybrid_and_module_building/metrology/metrology_header.md
              - 'Hybrid Metrology': itkstrips/hybrid_and_module_building/metrology/metrology_hybridmetrology.md
              - 'Module Metrology': itkstrips/hybrid_and_module_building/metrology/metrology_modulemetrology.md
          - 'ASIC Assembly': itkstrips/hybrid_and_module_building/asicassembly/asicassembly.md
          - 'Cheat Sheets':
              - 'Linux/Bash': itkstrips/hybrid_and_module_building/cheatsheets/cs_linuxbash.md
              - 'GNU Emacs': itkstrips/hybrid_and_module_building/cheatsheets/cs_emacs.md
      - 'Electrical Testing':
          - 'Single Module Testbox': itkstrips/electricaltesting/cheatsheet_PPB_module_9Nov23_v1.txt
    - 'Muon Collider':
        - 'References': muoncollider/references.md
        - 'MadGraph': muoncollider/madgraph.md
    - 'Past Student Thesis': thesis.md
