site_name: Birmingham Instrumentation Laboratory for Particle physics and Applications
site_description: Documenting our tools
site_author: BILPA Group
site_url: https://bilpa.docs.cern.ch/

repo_name: GitLab
repo_url: https://gitlab.cern.ch/bilpa/wiki
edit_uri: 'blob/master/docs'

theme:
  name: material

markdown_extensions:
  - attr_list

plugins:
  - search
nav:
    - Welcome: index.md
    - 'Official Page': http://www.ep.ph.bham.ac.uk/general/SiliconLab/index.html
    - 'Starter Guides':
      - 'ATLAS' : guides/atlas.md
      - 'Computing' : guides/computing.md
      - 'Electronics' : guides/electronics.md
      - 'Particle Physics' : guides/pp.md
      - 'Silicon Detectors' : guides/silicon.md
    - 'Procedures' :
      - 'Shutdown' : procedures/shutdown.md
    - 'Monitoring' :
      - 'InfluxDB + GrafAna' : monitoring/influx.md
    - 'ITk Strips':
      - 'Cold Jig':
          - 'Cold Noise Testing' : itkstrips/coldjig/cntesting.md
