site_name: Birmingham Instrumentation Laboratory for Particle physics and Applications
site_description: Documenting our tools
site_author: BILPA Group
site_url: https://bilpa.docs.cern.ch/

repo_name: GitLab
repo_url: https://gitlab.cern.ch/bilpa/wiki
edit_uri: 'blob/master/docs'

theme:
  name: material

markdown_extensions:
  - attr_list

plugins:
  - search
nav:
    - Welcome: index.md
    - 'Official Page': http://www.ep.ph.bham.ac.uk/general/SiliconLab/index.html
    - 'Starter Guides':
      - 'ATLAS' : guides/atlas.md
      - 'Computing' : guides/computing.md
      - 'Electronics' : guides/electronics.md
      - 'Particle Physics' : guides/pp.md
      - 'Silicon Detectors' : guides/silicon.md
    - 'Procedures' :
      - 'Shutdown' : procedures/shutdown.md
    - 'Monitoring' :
      - 'InfluxDB + GrafAna' : monitoring/influx.md
    - 'MC40 Irradiation Facility':
      - 'Documentation' : mc40/docs.md
    - 'ITk Strips':
      - 'Cold Jig':
          - 'Local Instructions' : itkstrips/coldjig/local.md
          - 'Software Installation' : itkstrips/coldjig/software.md
          - 'Thermal Cycling' : itkstrips/coldjig/thermalcycling.md
          - 'Cold Noise Testing' : itkstrips/coldjig/cntesting.md
      - 'Local Guides':
          - 'Hybrid-Building Slides' : https://indico.cern.ch/event/1303151/contributions/5480159/attachments/2682043/4652810/BHM_Hybrid_Building_BILPA_2023_07_11.pdf
    - 'Muon Collider':
        - 'References': muoncollider/references.md
        - 'MadGraph': muoncollider/madgraph.md
    - 'Past Student Thesis': thesis.md
